#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*             This image is deprecated.              *
*      We will not offer support for this image      *
*             and it will not be updated.            *
*                                                    *
*                                                    *
******************************************************
******************************************************

The last working tag is:
      1.4.0-ls145
We recommend the official image instead:
https://hub.docker.com/r/guacamole/guacd


******************************************************
******************************************************'
